# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: leading, trailing
Layout/DotPosition:
  Exclude:
    - 'app/helpers/application_helper.rb'

# Offense count: 6
# Cop supports --auto-correct.
Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'bin/bundle'

# Offense count: 1
# Cop supports --auto-correct.
Layout/EmptyLinesAroundArguments:
  Exclude:
    - 'app/helpers/application_helper.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, empty_lines_except_namespace, empty_lines_special, no_empty_lines
Layout/EmptyLinesAroundModuleBody:
  Exclude:
    - 'app/helpers/application_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment, AllowBeforeTrailingComments, ForceEqualSignAlignment.
Layout/ExtraSpacing:
  Exclude:
    - 'config/routes.rb'

# Offense count: 33
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleStyles, EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle.
# SupportedHashRocketStyles: key, separator, table
# SupportedColonStyles: key, separator, table
# SupportedLastArgumentHashStyles: always_inspect, always_ignore, ignore_implicit, ignore_explicit
Layout/HashAlignment:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IndentationWidth.
# SupportedStyles: aligned, indented
Layout/MultilineOperationIndentation:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'bin/bundle'

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: .
# SupportedStyles: space, no_space
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces.
# SupportedStyles: space, no_space
# SupportedStylesForEmptyBraces: space, no_space
Layout/SpaceBeforeBlockBraces:
  Exclude:
    - 'app/controllers/bands_controller.rb'
    - 'app/models/album.rb'
    - 'app/models/band.rb'
    - 'app/models/song.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment.
Layout/SpaceBeforeFirstArg:
  Exclude:
    - 'config/routes.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBrackets.
# SupportedStyles: space, no_space, compact
# SupportedStylesForEmptyBrackets: space, no_space
Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'

# Offense count: 1
Lint/DuplicateHashKey:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 2
Metrics/AbcSize:
  Max: 19

# Offense count: 1
Metrics/CyclomaticComplexity:
  Max: 8

# Offense count: 1
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 13

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 8

# Offense count: 3
# Cop supports --auto-correct.
Performance/StringReplacement:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'

# Offense count: 3
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'app/controllers/albums_controller.rb'
    - 'app/controllers/bands_controller.rb'
    - 'app/controllers/songs_controller.rb'

# Offense count: 20
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
Style/HashSyntax:
  Exclude:
    - 'app/controllers/songs_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/models/album.rb'
    - 'app/models/band.rb'
    - 'app/models/song.rb'
    - 'db/seeds.rb'

# Offense count: 5
# Cop supports --auto-correct.
Style/IfUnlessModifier:
  Exclude:
    - 'app/controllers/albums_controller.rb'
    - 'app/controllers/bands_controller.rb'
    - 'app/controllers/songs_controller.rb'
    - 'bin/bundle'

# Offense count: 17
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: require_parentheses, require_no_parentheses, require_no_parentheses_except_multiline
Style/MethodDefParentheses:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'bin/setup'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinBodyLength.
# SupportedStyles: skip_modifier_ifs, always
Style/Next:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/PerlBackrefs:
  Exclude:
    - 'bin/bundle'

# Offense count: 1
# Cop supports --auto-correct.
Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

# Offense count: 1
# Cop supports --auto-correct.
Style/RedundantInterpolation:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 10
# Cop supports --auto-correct.
Style/RedundantPercentQ:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Exclude:
    - 'app/controllers/albums_controller.rb'
    - 'app/controllers/bands_controller.rb'
    - 'app/controllers/songs_controller.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: .
# SupportedStyles: use_perl_names, use_english_names
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

# Offense count: 2
# Cop supports --auto-correct.
Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

# Offense count: 311
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'app/controllers/albums_controller.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/bands_controller.rb'
    - 'app/controllers/songs_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/models/song.rb'
    - 'bin/bundle'
    - 'bin/yarn'
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    - 'config/routes.rb'
    - 'config/spring.rb'
    - 'db/seeds.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
# IgnoredMethods: respond_to, define_method
Style/SymbolProc:
  Exclude:
    - 'app/controllers/bands_controller.rb'

# Offense count: 60
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 224
