
# Offense count: 1
Lint/DuplicateHashKey:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 1
Metrics/AbcSize:
  Max: 19

# Offense count: 3
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'app/controllers/albums_controller.rb'
    - 'app/controllers/bands_controller.rb'
    - 'app/controllers/songs_controller.rb'

# Offense count: 20
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
Style/HashSyntax:
  Exclude:
    - 'app/controllers/songs_controller.rb'
    - 'app/models/album.rb'
    - 'app/models/band.rb'
    - 'app/models/song.rb'
    - 'db/seeds.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/IfUnlessModifier:
  Exclude:
    - 'app/controllers/albums_controller.rb'
    - 'app/controllers/bands_controller.rb'
    - 'app/controllers/songs_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinBodyLength.
# SupportedStyles: skip_modifier_ifs, always
Style/Next:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/RedundantInterpolation:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 10
# Cop supports --auto-correct.
Style/RedundantPercentQ:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Exclude:
    - 'app/controllers/albums_controller.rb'
    - 'app/controllers/bands_controller.rb'
    - 'app/controllers/songs_controller.rb'

# Offense count: 294
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'app/controllers/albums_controller.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/bands_controller.rb'
    - 'app/controllers/songs_controller.rb'
    - 'app/models/song.rb'
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    - 'config/routes.rb'
    - 'config/spring.rb'
    - 'db/seeds.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
# IgnoredMethods: respond_to, define_method
Style/SymbolProc:
  Exclude:
    - 'app/controllers/bands_controller.rb'

# Offense count: 51
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 224
