require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - bin/*

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Exclude:
    - db/seeds.rb
  Max: 100

Metrics/BlockLength:
  Exclude:
    - config/routes.rb

Metrics/AbcSize:
  Max: 12

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/MessageSpies:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/MixinUsage:
  Exclude:
    - script/*
