
# Offense count: 1
Lint/DuplicateHashKey:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 1
Metrics/AbcSize:
  Max: 19

# Offense count: 51
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 224
