name: Greetings

on: [pull_request, issues]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "That's your first issue in this repo! Thanks and welcome! 🎉"
        pr-message: "That's your first pull request in this repo! Thanks for contributing! ❤️"
